services:

  database:
    container_name: db
    image: postgres
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    command: ["postgres"]
  
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    command: ["sh", "-c", "sleep 10 && python main.py"]
    environment:
      ENVIRONMENT: "production"
    volumes:
      - .:/app
    depends_on:
      - database
  
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
  
volumes:
  postgres_data:      